language: generic
sudo: false
before_install:
  - curl -fsSkL https://gist.github.com/rejeep/ebcd57c3af83b049833b/raw > x.sh && source ./x.sh
  - evm install $EVM_EMACS --use --skip
  - cask
env:
  - EVM_EMACS=emacs-24.4-travis-linux-xenial
  - EVM_EMACS=emacs-24.5-travis-linux-xenial
  - EVM_EMACS=emacs-25.1-travis-linux-xenial
script:
  - emacs --version
  - make test
